# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

main_loop_gh <- function(X, G, model_id, model_type, in_zigs, in_nmax, in_l_tol, in_m_iter_max, in_m_tol, anneals, t_burn = 5L) {
    .Call(`_mixture_main_loop_gh`, X, G, model_id, model_type, in_zigs, in_nmax, in_l_tol, in_m_iter_max, in_m_tol, anneals, t_burn)
}

gh_e_step_internal <- function(X, G, model_id, model_type, in_m_obj, init_zigs, in_nu = 1.0) {
    .Call(`_mixture_gh_e_step_internal`, X, G, model_id, model_type, in_m_obj, init_zigs, in_nu)
}

main_loop <- function(X, G, model_id, model_type, in_zigs, in_nmax, in_l_tol, in_m_iter_max, in_m_tol, anneals, t_burn = 5L) {
    .Call(`_mixture_main_loop`, X, G, model_id, model_type, in_zigs, in_nmax, in_l_tol, in_m_iter_max, in_m_tol, anneals, t_burn)
}

e_step_internal <- function(X, G, model_id, model_type, in_m_obj, init_zigs, in_nu = 1.0) {
    .Call(`_mixture_e_step_internal`, X, G, model_id, model_type, in_m_obj, init_zigs, in_nu)
}

main_loop_st <- function(X, G, model_id, model_type, in_zigs, in_nmax, in_l_tol, in_m_iter_max, in_m_tol, anneals, t_burn = 5L) {
    .Call(`_mixture_main_loop_st`, X, G, model_id, model_type, in_zigs, in_nmax, in_l_tol, in_m_iter_max, in_m_tol, anneals, t_burn)
}

st_e_step_internal <- function(X, G, model_id, model_type, in_m_obj, init_zigs, in_nu = 1.0) {
    .Call(`_mixture_st_e_step_internal`, X, G, model_id, model_type, in_m_obj, init_zigs, in_nu)
}

main_loop_vg <- function(X, G, model_id, model_type, in_zigs, in_nmax, in_l_tol, in_m_iter_max, in_m_tol, anneals, t_burn = 5L) {
    .Call(`_mixture_main_loop_vg`, X, G, model_id, model_type, in_zigs, in_nmax, in_l_tol, in_m_iter_max, in_m_tol, anneals, t_burn)
}

vg_e_step_internal <- function(X, G, model_id, model_type, in_m_obj, init_zigs, in_nu = 1.0) {
    .Call(`_mixture_vg_e_step_internal`, X, G, model_id, model_type, in_m_obj, init_zigs, in_nu)
}

